[package]
name = "crynn-shell"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt", "macros", "process", "time"] }
winit = "0.29"  # for launching the crynn browser 
egui = "0.27"
crynn-engine_bridge = { path = "../engine_bridge" }


